#' Update values by reference to dictionary.
#'
#' @export
#'
#' @author Finlay Campbell (\email{finlaycampbell93@@gmail.com})
#'
#' @param value A vector of values to be updated.
#'
#' @param dictionary A dictionary as generated by \code{update_dictionary}.
#'
match_dictionary <- function(value, dictionary) {
  mtch <- match(value, dictionary$value)
  value[which(!is.na(mtch))] <- dictionary$reference[mtch[!is.na(mtch)]]
  return(value)
}
